### ISSUE TITLE
A brick should know which of its outputs are actually needed

### ISSUE THREAD

**Issue by JanWP** [populse/populse_mia#107]
**Expected behavior**
When coding a brick for MIA, there is a trade off to be found in terms of ease of use and atomicity of the action performed. Fewer, more complex bricks are sometimes easier to handle for the user and computationally more efficient. Such bricks may propose several outputs, not all of which may be necessary for all use cases. Generating these outputs may require computations, which might be skipped if some output is not required.

**Actual behavior**
Currently, a brick has no way of knowing which outputs are actually used in a pipeline, so all computations need to be performed, and all files are generated on the hard drive and in the database. I consider this wasteful in terms of computation and storage resources, and this unnecessarily clutters the database. 

To work around this, a developer could choose to add input parameters to let the user explicitly switch on or off the generation of certain outputs. Since the user already provides that same info by connecting an output to other bricks or exporting it, this would make such bricks much more cumbersome to use than necessary when building and modifying pipelines.

**Comment by servoz** [comment]
This is a hot point that we have started to discuss with @denisri and @sapetnioc 

Personally, I think it is not unreasonable for atomic bricks to be aware of their environment in order to react according to. This obviously creates risks, but it produces more freedom, and therefore intelligence.

It is the eternal debate about freedom versus security ((by default, I will always be on the freedom side : -)

I link this ticket to a one that I open presently in capsul, in order to take stock and allow the exchanges and decisions, as soon as possible, on this subject

**Comment by sapetnioc** [comment]
Processes are not always executed in the same job as the one that owns the
Pipeline. In a hopefully not so far future, each process will be executed
in its own Python process. Therefore, anything that a Process may use must
be explicitely identified and transfered to a job. There are only three
things that Capsul can transfer to a job in all known execution contexts
(including computing clusters) : command line parameters, files and
environment variables. We can assume that the parameters of a process are
already serialized/deserialized between job by Capsul (this is not true for
every parameter type yet). I suggest that we keep using parameters for
storing anything that can be used by a process. If we need to provide a
process with special information, we could decide to have a parameters with
special name such as _the_capsul_process_environment. If necessary, Capsul
could automatically provide a value for such a parameter if a process
declares it. This would make any context expiciltely given to a process so
we can eventually store all parameters in an execution history database
allowing to re-run exactly the same process even if the context has
changed. Using parameters would also avoid changing the execution machinery
of Capsul.

That said, we must decide how to inform a process that an output parameter
is useless. One possibility would be to ask Capsul to remove any useless
value. The process would simply ignore all parameters that are undefined.
That way we would not need to add any special parameter to solve this
issue. There are many other possibilities that we can discuss.

**Comment by JanWP** [comment]
I'm not sure I understand this answer correctly, but the execution model evoked here seems rather different from the one used by mia_processes. From the little I have seen, my impression was that in mia_processes a brick decides itself on the names of the files it will generate and provides methods for the execution engine to query this information at the moment of initialization. It does not take the names of the output files as input parameters. It seems to me, that the decision on which output files to generate should be made at the moment of initializing the brick, not at the moment of running it. The initialization presumably is performed within the same job as the one that owns the pipeline, or have I misunderstood anything?

To me there also seems to be an issue with the interaction with the database. Bricks will frequently require access to the database entries of their input files. This means that we will need to serialize these as well and pass them to the brick at execution time and parse them again. The amount of data in the database for each scan may be non-negligible (for pre-clinical data, the entire pulse program and all original scan parameter files etc. may be included). This can probably be done, but what is the expected cost in performance due to the associated overhead? We are not doing great in performance currently, and improvements will be crucial for wider adoption of MIA, I think. What is the benefit to this execution model in a single-workstation deployment of MIA, which I would expect to remain the vast majority of our deployments?

Granularity at the level of individual bricks for launching separate jobs seems extremely small. Should we not look to launch jobs containing sub-pipelines, or even just the entire pipeline if it is not too large? In which case, the executable called would be an instance of a pipeline execution engine, which knows about inputs and outputs of the bricks.

**Comment by servoz** [comment]
@JanWP,
This is an attempt.
please make an installation of populse_mia from https://github.com/servoz/populse_mia.git
In a nutshell:
The plug object is passed during the initialisation of the pipeline to the personal brick. Take care to have  plugs=None in the list_outputs method definition of your brick.
It is just necessary to check in the list_outputs method, if the plug is linked by using, 
if plugs[plug_name].links_to:  
            # this plug is linked in output
            outputs[plug_name] = ['WahtYouWant.nii]
            # do what you what if the plug is linked in input
You can also check if the plug is linked in input:
if plugs[plug_name].links_from: 
            # etc ...
So at initialisation time you can do something depending of the linked state of the plug. If you do nothing the plug stay with the default trait value (for example in case of a file it will be in ["<undefined>", traits.Undefined]). At the run time, in the run_process_mia(self) of your brick, it will be possible to detect if the plug is linked (if self.YourNamePlug in ["<undefined>", traits.Undefined]: it is not linked) ... etc
This is a first try, I (we) need to check if it is working fine in all context (this seems to work fine with my brick but I  not yet checked with nipype bricks for example !)

**Comment by JanWP** [comment]
Thanks a lot! I'll have a look ASAP.

**Comment by servoz** [comment]
The first tests on pure nipype bricks seem conclusive. 

We can leave this ticket open for as long as it takes to check that there is no side effects. If in a few days we haven't detected any problems (and if the change really allows to have access to the state linked or not of the plugs) we will merge the fork to master and close this issue.

**Comment by servoz** [comment]
@JanWP,
I just added a Smooth brick (based on the SPM Smooth process) in the github.com/populse/mia_process library (so you can update your mia_processes library in your station <by using python3 setup install etc...> , and populse_mia will add automatically this new version at next startup. I have set a minimum example test for the link of an imaginary plug (test_files output). This should illustrate the use (in fact very simple :-)))

**Comment by JanWP** [comment]
Confirmed to be working - thanks a lot!! A simple and functional solution.

I could see two potential issues we may want to think about before adopting this, though:
1) Do we expect a scenario where the call to the _list_outputs_ method needs to be serialized because it is run on a different machine? In that case, passing the _plugs_ object as is may take some time, since it contains references to everything in the entire pipeline.
2) Do we expect bricks to be well-behaved? With this solution we need to trust them, because this object is passed by reference and now the brick can monkey with the entire pipeline. This can be good or bad. It certainly gives a lot of power to the brick. If the brick for example does a 
```old_link = plugs[plug_name].links_to.pop()```, the link is gone from the pipeline.

**Comment by servoz** [comment]
1. Yes, if the brick is a pipeline, the plugs object actually has all the plugs in that pipeline. If the pipeline is large it can be a problem. Once again, I apologize for focusing currently only on the personal computer version (with only one-core processor :-)  and of course do not hesitate to add possible side effects on the case of calculation on several machines or Grid computing.
2. . As we had previously discussed (just above) with @denisri and @sapetnioc , this functionality introduces risks... it may be the cost of freedom...
More seriously, it may be necessary to provide safeguards, because this feature does introduce risks of making mistakes. I am very busy with the question of initialisation and dependency ([discussed in the group messages](https://github.com/orgs/populse/teams/populse_member/discussions/16)) and I confess that I don't have time right now to go deeply into the development of his safeguards , but it would indeed require serious thinking.

**Comment by servoz** [comment]
So we leave this ticket open until we finish thinking about it?

**Comment by JanWP** [comment]
I think this is maybe just a point to keep in mind for now. The original issue is fixed, and well fixed at that. I fully understand that the remaining issues I mentioned are rather low-priority. However, I did want to write them down somewhere to not forget, because I thought the risk of a brick changing the rest of the pipeline was not mentioned before.

**Comment by servoz** [comment]
I totally agree with you, and I also try to write as much as possible here to keep ideas somewhere!!!!!
But I'm afraid I'll end up losing ideas if we close ticket ... (in fact I am torn between the very great desire to close issues - I have the feeling that we haven't close one since early July ! and the desire not to lose ideas - which are our greatest wealth !)

So, i think it is very urgent to wait to close this ticket ..

**Comment by M40V** [comment]
Currently the modifications done to the plug object inside the brick do not pass on to the main pipeline process. It is not possible to modify the project pipeline from the plug object.

Example:
We used the code `old_link = plugs["smoothed_files"].links_to.pop()` inside a Smooth brick.
Before calling `process.list_outputs(plugs=pipeline.nodes[node_name].plugs)` on this brick, the value of `pipeline.nodes[node_name].plugs` was 

`{'in_files': <capsul.pipeline.pipeline_nodes.Plug object at 0x7f718008f308>, 'fwhm': <capsul.pipeline.pipeline_nodes.Plug object at 0x7f718008f2b0>, 'data_type': <capsul.pipeline.pipeline_nodes.Plug object at 0x7f718008f200>, 'implicit_masking': <capsul.pipeline.pipeline_nodes.Plug object at 0x7f718008f1a8>, 'out_prefix': <capsul.pipeline.pipeline_nodes.Plug object at 0x7f718008f0f8>, 'smoothed_files': <capsul.pipeline.pipeline_nodes.Plug object at 0x7f7180082c50>}`

after calling the method, it was
`{'in_files': <capsul.pipeline.pipeline_nodes.Plug object at 0x7f718008f308>, 'fwhm': <capsul.pipeline.pipeline_nodes.Plug object at 0x7f718008f2b0>, 'data_type': <capsul.pipeline.pipeline_nodes.Plug object at 0x7f718008f200>, 'implicit_masking': <capsul.pipeline.pipeline_nodes.Plug object at 0x7f718008f1a8>, 'out_prefix': <capsul.pipeline.pipeline_nodes.Plug object at 0x7f718008f0f8>, 'smoothed_files': <capsul.pipeline.pipeline_nodes.Plug object at 0x7f7180082c50>}`

**Comment by servoz** [comment]
Thanks @M40V!
So, it seems that for the point 2., the brick sees its environment, but it can't change it (I didn't have time to look seriously at this problem)? In that case, is that exactly what we wanted?

For point 1., it might be interesting to try some tests, because it seems to me that we are still far from using this possibility.

So if there is no other example of risk (point 2.), I propose to close this ticket (say at the end of this week).

**Comment by M40V** [comment]
After further testing, I was able to modify the environment from the brick. We can't modify the plug object from the brick, but we can modify the objects where it points to (like the links). The module copy.deepcopy doesn't solve this issue.

**Comment by JanWP** [comment]
Yes, this works. Thanks a lot, @M40V!

From looking at [the code](https://github.com/populse/populse_mia/blob/5f45b59193363ad08e4b94bc60a8cfe137712a72/python/populse_mia/user_interface/pipeline_manager/pipeline_manager_tab.py#L790):
```python
pipeline_plugs = {}
for key in pipeline.nodes[node_name].plugs:
    pipeline_plugs[key] = False
    if pipeline.nodes[node_name].plugs[key].links_to:
        pipeline_plugs[key] = True
    elif pipeline.nodes[node_name].plugs[key].links_from:
        pipeline_plugs[key] = True

(process_outputs, self.inheritance_dict) = process.list_outputs(plugs=pipeline_plugs)
```
I think this can be simplified, though. First, [further up](https://github.com/populse/populse_mia/blob/5f45b59193363ad08e4b94bc60a8cfe137712a72/python/populse_mia/user_interface/pipeline_manager/pipeline_manager_tab.py#L703), we already defined:
```python
node = pipeline.nodes[node_name]
```
so we don't need to type out ```pipeline.nodes[node_name]``` each time. Second, I think ```pipeline_plugs``` is not the best name for that variable, since pipelines don't have plugs. Nodes do. And we don't collect plugs, we collect their connection status. And third, we can use list comprehension to build the dictionary:
```python
is_plugged = {key: (bool(node.plugs[key].links_to) or bool(node.plugs[key].links_from))
              for key in node.plugs}
(process_outputs, self.inheritance_dict) = process.list_outputs(is_plugged=is_plugged)
```
Does this make sense? Any reason not to rename the keyword argument of _list_outputs_ now to ```is_plugged``` (or simply ```plugged``` if you prefer), while there are not yet many bricks that need to be modified? This keyword argument is part of our user-facing API, which means that 
1. we should choose the name carefully to be the most intuitive with respect to its content, and 
2. changing it later means many bricks will need to be changed, which is a hassle.

**Comment by servoz** [comment]
@JanWP, I totally agree with that.
Your proposal is elegant, therefore concise, effective, and certainly robust. 
OK for me!

**Comment by servoz** [comment]
@JanWP, the change is now effective on master.
I guess we can now close this ticket?

**Comment by JanWP** [comment]
Absolutely! Thanks for integrating the changes (sorry I was too lazy to make a PR). 

Just a tiny thing: [this line](https://github.com/populse/populse_mia/blob/393e220f902d94dbc2b454adc53b0da2d539ce86/python/populse_mia/user_interface/pipeline_manager/pipeline_manager_tab.py#L790) is left over from the old code and superfluous now.

**Comment by servoz** [comment]
The line is removed.
Please close this ticket if you think that everything is fixed now.

**Comment by JanWP** [comment]
Yes, all good as far as I can see. Thanks again!
