### ISSUE TITLE
data selection is broken

### ISSUE THREAD

**Issue by denisri** [populse/populse_mia#154]
**Describe the bug**

In the pipeline manager, I select a process ("Smooth" for instance), export its plugs, then select "filter" for the "in_files" parameter. When I select a data in the database, I only get [undefined], and there is an error in the terminal:

**Generated error**
```
<class 'SyntaxError'>: invalid syntax (<string>, line 1).
```

**To Reproduce**
1. open / create a project with imported data
2. go to the pipeline manager
3. drag/drop a Smooth process rom mia_processes/preprocess
4. export its plugs
5. select "Filter" for the parameter "in_files", and chose any data
6. the error occurs and in_files gets the value [undefined]

**Expected behavior**
get a filename as parameter value

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 18.04
 - Populse_MIA version 1.3.0 (master)

**Additional context**

**Comment by denisri** [comment]
in node_controller.py, in PlugFilter.set_plug_value(), it seems that tag_name is "&FileName" whereas it's expected to be "FileName".
I don't know where this value comes from, I have not investigated the whole process.

**Comment by servoz** [comment]
With my configuration, I do not observe this problem.
As I recall, (but we have to be careful what I remember!) it seems to me that it's @JanWP  who had problems with extra characters with is config (but I never had any).
If I'm not mistaken he had made some changes including this filtering ? 
What we can do is, if your PR solves your problem, I'll test it on my side and if it doesn't introduce a problem with my config, we can consider that it should fix the problem for everyone (maybe it would be better if @JanWP  also tests your PR on his side to be really sure, before to merge the PR?) I'm sorry I didn't take the time to read all the codes (just your PR, that seems to make sens) and try to understand, but if the proposed tests work, I think we'll be able to merge this PR ?

**Comment by denisri** [comment]
My change is just a 2 lines modif that removes '&' from the tag name if there is one, so should not harm, but if there is really no reason to get this '&' here, then we should rather fix it upstream instead of where I have done it. The real question here that I can't answer is: why do I get this '&', where does it come from ?

**Comment by servoz** [comment]
As far as I remember, @JanWP had problems with the ampersand characters added by Qt (see 9e78ff8fed50d097b9801441aedc742fb4d82867). I have never observed this problem with my configuration, so I confess that I never looked at it because @JanWP seemed to have solved the problem. It should tell us more soon.
For my part I will test your PR (just for form, because I agree that the few lines of change should not introduce any problem for me!).

**Comment by denisri** [comment]
9e78ff8fed50d097b9801441aedc742fb4d82867 seemed to fix the same kind of problem, but somewhere else in the GUI, in places there can probably be some keyboard shortcuts to activate tabs (the '&' is used for that I think). Here it is in a data table, I don't understand how/why Qt is adding some '&', and why it does it for me now whereas it did not before and still doesn't for you.

**Comment by servoz** [comment]
Exactly!!!
And as I said before, because I've never had this problem, I admit I never invested any time on it since @JanWP spend time to solve it from his side. That's why I'm looking forward to his point of view on this (I have no memories on this problem)!

**Comment by servoz** [comment]
This story with Qt has always amazed me ... but there are many things that amaze me by lack of knowledge ... I confess that I always had the feeling that it could come from the lark library ... but without any certainty since I never investigated this problem. Is this problem always observed in link with database queries  (which seems to be the case in this ticket) ??? in this case lark library could be a good candidate ?

**Comment by denisri** [comment]
Interesting idea, I'll check my lark version, and tell you...

**Comment by denisri** [comment]
Well, I actually had a lark-parser problem (an old install was shadowing the right one in ~/.local/lib/python, thanks pip doing lots of things behind your back... did I tell you I don't like pip ?), but it didn't change the behaviour in this problem. (it fixed search/requests in the database, however :) )

**Comment by servoz** [comment]
Yes, I know you don't like pip :smiley:

**Comment by servoz** [comment]
6 days later, no feedback from @JanWP. 
@denisri, I assume your 37436da commit fixes this problem? It could be interesting to fix it upstream, but given the little feedback I fear that this ticket will remain pending for a long time and I propose to close it for now (it will always be possible to reopen it later if necessary).
