### ISSUE TITLE
[Iteration enhancement] Iteration: database indexing issues

### ISSUE THREAD

**Issue by servoz** [populse/populse_mia#217]
Observed in the 3 iteration modes [described in the documentation](https://populse.github.io/populse_mia/html/documentation/pipeline_manager.html#pipeline-iteration).

Only the last patient in the iteration is indexed in the database after `initialisation` (and then `run`). On the other hand, all the expected data can be found in the derived_data directory of the project, after the `run`.

**Comment by LStruber** [comment]
It is not really a problem of indexing database, because the database write what we ask it for (when calling `_register_node_io_in_database` l.1485 of `pipeline_manager_tab.py`). It is rather a problem of completion or completion_engine either in process_mia or capsul side.
I think that when initializing the pipeline, we should iterate the `nodes` (except the first one that represent the complete pipeline) as many times as there are subjects by creating new nodes (rather than referencing the actual node). This should be done either in `process_mia.py` (`complete_parameters` function) or in capsul completion engine.

**Comment by sapetnioc** [comment]
Creating nodes for each subject may become a problem when there are a lot of subjects. Having a complete representation of all nodes is what we do in BrainVISA and pipeline creation becomes really slow with a few hundreds of subjects (but nodes have better optimization in Capsul). I do not know MIA very well so my suggestion may be wrong but could it be possible to perform indexation in another way ? For instance, instead of using the pipeline parameters to decide what to put in the database, have each process write a little file (JSON for instance) indicating what to put in the database. At the end of the whole pipeline execution, MIA would parse these files to update database.

**Comment by denisri** [comment]
I didn't get time to work on MIA recently, and I didn't follow the issues closely. I completely agree that there is a problem with indexing iterations, because the database records processes instances with one set of parameters, while in iterations they get several values sets.
Duplicating processes instances is precisely what we wanted to avoid when designing Capsul, as Yann says it. Moreover there is an additional distinction that is not made in MIA between two entities that we call "pipeline" and "workflow", which is maybe the key of the problem here. For us, and in Capsul, the pipeline is a "theoretical schema", each node of a pipeline is a "potential" process, but is not necessarily one: some nodes are not processes (switches for instance), a process may not be used (for an inactive node) and a process may be used several times (in an iteration). So maybe what should be indexed in the database for a run is not the pipeline nodes instaces, but the "workflow". The workflow reflects the actual run: only nodes which are processes (jobs) are represented there, and each run gets an individual instance (in an iteration, one job is created for each iteration). Thus I come to think that the workflow jobs should be indexed, but not the pipeline. Well I haven't thought much about it yet so I'm not sure it is the solution, but I think that what the indexation does (or should do) looks closely like the pipeline/workflow transformation, which is not trivial and should probably not be coded twice.

**Comment by LStruber** [comment]
Thank you both for your answers,
I understand well that duplicating processes is (at least) suboptimal.
I was not aware of the distinction @denisri raised between `pipeline` and `workflow` objects in Capsul and this point is very interesting. However, if I'm not wrong, the `workflow` object is created at the beginning of the "Run", whereas database is currently indexed during initialization. Then, using `workflow` to populate database should be deeply related to the past reflection you had on "when indexing database" (see #181 and #194). I see two solutions:
1. (quick and somewhat dirty) keeping current situation - indexing database during initialization - create an object that contains information of each node (deepcopies of necessary attributes) to populate the database
2. index the database during the soma_workflow run, and then populate it by retrieving `workflow` object in MIA. I do not realize how much coding time this solution represents.

I'm currently working on solution 1 that should (hopefully) allow to quickly close this issue, but I feel like we could have a discussion on point 2 (could we organize a meeting, via Zoom or whatever ? This could be the opportunity to introduce myself). In an ideal world (which is certainly conversely correlated with fast issues fixing), I think that populate database "temporarily" during the initialization is interesting for the user to see how many files will be created (names in data manager tab could be grayed out or italic). During the run, file names could became black when files are really created, allowing the user to better appreciate the status of the run. What do you think ?

**Comment by LStruber** [comment]
fixed with commit c9699ba6cba6ed34bc7da2f3b937879734297330
(solution 1. was implemented)

**Comment by servoz** [comment]
I have just tested with Smooth brick from mia_processes on 2 patients.
- We have now 2 indexations in the database, each for the smooth image of the 2 patients: cool !!!!
- **But**:
    - the name of the brick is not good in the special tag "Bricks" ( `main` while we would like `smooth_1`)
![Screenshot from 2021-11-09 17-56-33](https://user-images.githubusercontent.com/37933899/140970029-df8874c7-1ae7-489f-bb69-102d3cb75568.png)
    - the value of parameters in this tag are suboptimal.
        - we would like to have at least the value of the input files (here: in_files is Undefined) because this tag should allow us to reconstruct afterwards the history to produce the final image. But also all other tags (`matlab_cmd`, `output_directory`, etc.)
![Screenshot from 2021-11-09 18-02-20](https://user-images.githubusercontent.com/37933899/140972743-c1c62536-7e04-45c7-a52c-d23c936e8666.png)
I also tested the smooth brick of mia_processes on 1 patient (without iteration). Also missing values for some tags (`matlab_cmd`, `output_directory`, etc.). This was not the case before the commits for this ticket (tested by setting HEAD to ab93fefa).
I think we could consider either to rollback to before the commits for this ticket on master and continuing the work on a development branch or fixing this lost parameters issue in the special Bricks tag as a priority on master, as there seems to introduce a regression (at the same time as an improvement, certainly!).

**Comment by LStruber** [comment]
My bad! Indeed I did not compare the values inside the brick tag before and after changes. However, what I do not understand is that when I run an iteration on a Smooth on my computer the name of the brick tag is good :
![smooth](https://user-images.githubusercontent.com/86590799/140989996-4270701a-3a6f-40f3-903d-4cc7699e091d.png)

I'll try to figure out what's going on here, and maybe the wise thing to do would be to rollback the master branch while I continue working on the issue branch I kept.

**Comment by LStruber** [comment]
I added a line (and pushed it on master) that seems to correct bricks tag values of smooth_1 on my computer... Nonetheless, since behavior seems to be a bit different on your (@servoz ) computer (or in the manner you iterate), could you check what you got now ?

![smooth](https://user-images.githubusercontent.com/86590799/140996382-e673810b-b8c9-44ee-9668-822024d7aac1.PNG)

**Comment by servoz** [comment]
I just tested with the smooth brick of mia_processes:
- on 1 patients (without iteration):
  - Thanks to your last commit, the regression seems to have disappeared. Nice!
- 0n 2 patients ([with iteration / Via Input_Filter brick/process and with use of the iteration table](https://populse.github.io/populse_mia/html/documentation/pipeline_manager.html#with-use-of-the-iteration-table)):
  - I always see the name 'main' instead of the real name of the brick.

Ok, since the regression has disappeared I think we can avoid rolling back the master branch. On the other hand we should fix this name issue ASAP to be able to close this ticket.

PS. I think I have figured out why I am observing this name issue and you have not!!!
There are 3 ways to iterate:
   - [Via a regular iterative pipeline (without use of the iteration table)](https://populse.github.io/populse_mia/html/documentation/pipeline_manager.html#via-a-regular-iterative-pipeline-without-use-of-the-iteration-table): I observe like you the good brick/node name.
   - [Via Input_Filter brick/process (without use of the iteration table)](https://populse.github.io/populse_mia/html/documentation/pipeline_manager.html#without-use-of-the-iteration-table): I always see the name 'main' instead of the real name of the brick.
   - [Via Input_Filter brick/process and with use of the iteration table](https://populse.github.io/populse_mia/html/documentation/pipeline_manager.html#with-use-of-the-iteration-table):  I always see the name 'main' instead of the real name of the brick.

Naively, we can think that the last issue, to be fixed to close this ticket, is strongly correlated with the Input_filter brick?

**Comment by LStruber** [comment]
I tried iterating with an input filter brick (without use of the iteration table), and I still see the smooth name in the bricks tag. I did not manage to reproduce the "main" name issue. Any idea ?

MOREOVER when I use an filter brick, whatever the filter I choose (exp_type = anat for example), the initialization is done on all the database (and not only on the filtered files as expected), which is quite problematic. In pipeline manager, after initializing, the "outputs" field of the filter is automatically set to all files in the database

**Comment by LStruber** [comment]
I think that the issue of "main" name is not an initialization issue;
When iterating a smooth node using Input_filter brick, its name is changed into "main" inside the iteration node. Then we should look rather in iteration than in initialization

![iteration](https://user-images.githubusercontent.com/86590799/141144175-f72ec28f-7503-48cf-b3c7-c734f4a95b59.PNG)

**Comment by servoz** [comment]
Oh yes, I see...
I think you're right.
The problem must be more on the iteration side, then.
I guess the brick/node/process name is not properly initialised/caught (`main` makes me think of a default value like when a widget is not given a title like for example with QGraphicsView.widgetsandWindowTitle()).
Have you already taken a look at capsul.qt_gui.widgets.pipeline_developper_view.PipelineDevelopperView()?
It won't give you the final solution (that will be more in the iteration part), but it can help you understand a bit about the concepts and objects under the hood.

**Comment by denisri** [comment]
Yes the "main" name is a default (hard-coded) node name used when building the iteration in MIA. The code is in `populse_mia.user_interface.pipeline_manager.pipeline_manager_tab` in `build_iterated_pipeline()`: when we iterate a process using an input filter node, the iteration will use each output file of the filter node as a single input for the iterated process (one per iteration). If the process (like many nipype/SPM nodes) expects a list as input, then we must transform the single file of the current iteration into a list, inside the iteration. To do so we transform the iterated process into a small pipeline containing the iterated process under the node name "main", and a `ReduceNode` for each filtered input, which will transform the filename into a list (list of 1 item). "main" is probably the best name, but using the process name could lead to conflicts if by chance it had the same name as the one we assign to `ReduceNode`s. But we may find a better way, for sure.

**Comment by denisri** [comment]
In a general way, using the "short" node name of a process in a pipeline as a brick identifier will likely often be little informative, because many pipelines will assign node names which are not really clear and specific... but I admit I don't have a very good naming solution...

**Comment by denisri** [comment]
> Thank you both for your answers, I understand well that duplicating processes is (at least) suboptimal. I was not aware of the distinction @denisri raised between `pipeline` and `workflow` objects in Capsul and this point is very interesting. However, if I'm not wrong, the `workflow` object is created at the beginning of the "Run", whereas database is currently indexed during initialization. Then, using `workflow` to populate database should be deeply related to the past reflection you had on "when indexing database" (see #181 and #194). I see two solutions:
> 
>     1. (quick and somewhat dirty) keeping current situation - indexing database during initialization - create an object that contains information of each node (deepcopies of necessary attributes) to populate the database
> 
>     2. index the database during the soma_workflow run, and then populate it by retrieving `workflow` object in MIA. I do not realize how much coding time this solution represents.
> 
> 
> I'm currently working on solution 1 that should (hopefully) allow to quickly close this issue, but I feel like we could have a discussion on point 2 (could we organize a meeting, via Zoom or whatever ? This could be the opportunity to introduce myself). In an ideal world (which is certainly conversely correlated with fast issues fixing), I think that populate database "temporarily" during the initialization is interesting for the user to see how many files will be created (names in data manager tab could be grayed out or italic). During the run, file names could became black when files are really created, allowing the user to better appreciate the status of the run. What do you think ?

Sorry for answering late. There has been some discussion on what is the right time to index the database, and I don't remember there was one obviously very good answer. So for now we continue to do it at init time (as in your option 1).
If we go on with it, we can also consider building the workflow at init time too (but not start it), which would have a double benefit: 1) check that it is correct at init time, 2) possibly use it for indexation as in option 2.
But of course it's not the only solution. I would just like to avoid re-writing code mimicking the workflow generation for indexation purpose, which will necessarily make more code to maintain, end up with a different implementation, a probably different workflow, and will likely not model the exact run and induce inconsistencies. If needed, we may call the workflow generation code (`capsul.pipeline.pipeline_workflow.workflow_from_pipeline()`) even if it will be done twice when actually running.

**Comment by servoz** [comment]
I had not yet taken the time to read the method (unless I'm mistaken, it was you, @denisri , who wrote it when we moved to V2?) populse_mia.user_interface.pipeline_manage.pipeline_manager_tab.PipelineManagerTab.build_iterated_pipeline() and [I see that the name 'main' is indeed hard-coded in it](https://github.com/populse/populse_mia/blob/aab3bc9ab2f1964606edab9a3be1cbf139f05c67/python/populse_mia/user_interface/pipeline_manager/pipeline_manager_tab.py#L903).

The special Bricks tag in the data browser has been designed to allow to have the history of a data created in mia.
I think this is a very important feature in mia and to have the name of the node (because toto process can gives toto_1 and toto_2 nodes in the same pipeline) that has been used is not an option.

I understand your fear about the confusion in the names if they are not managed. Unless I'm mistaken, if the same process is used several times in a pipeline there is a _1, _2 added for the corresponding nodes/bricks. The risk is more to use processes with the same name, maybe there should be a test that forbids it.

Anyway, we maybe don't need to go that far. Maybe we can just keep 'main' as process name and put the name of the starting node on the iteration node and in the special Bricks tag.
There is also the name [iteration] for the iteration node/brick which I think is not very informative and could be improved (something like toto[iteration]?, I think we would like to know what is the node/process iterated).

**Comment by LStruber** [comment]
resolved with commits e2fac7b7f483770aea5fc44248596d0acfdf587f, 692fbcd4ba56fdbc628483eac4264aac700b6f5e and 62f586232721bdb270f515fa69073d59c0bae91c. (Sorry @servoz for the "multiple commits")
1. When iterating over a single brick, 'main' name inside iterated pipeline has been replaced by the node name (and not the process name to avoid possible conflicts) --> Is this ok or is there something I misunderstood @denisri ?
2. Now, iterated node is named after the subpipeline or brick inside it (for example `iterated_Spatial_preprocessing` or `iterated_Smooth`). Note that when the subpipeline has no name (it was not saved), iterated node is name `iterated_Pipeline`. **Unfortunately, this is always the case in iteration mode 1 (Via a regular iterative pipeline (without use of the iteration table)) because we create an unsaved pipeline**

This has been tested in the 3 iteration modes, with bricks Smooth (SPM) and Spatial_preprocessing.

**Comment by LStruber** [comment]
The naming is suboptimal for FSL bricks (tested on Smooth brick)
Brick tag is `iteration_pipeline.iterated_Smooth` and smooth_1 inside iterated brick is renamed "Smooth" (I think it was already the case before previous commits, and would not be the result of a regression)

**Comment by LStruber** [comment]
fixed with commit 0d9939bcd9ac7a139bd7eee028b634c0986db17b
Now tested in the 3 iteration modes, with bricks Smooth (SPM), Smooth (FSL) and Spatial_preprocessing.
